### ISSUE TITLE
Showing `Call to undefined function ZendXml\simplexml_import_dom()` in the news feed

### ISSUE THREAD

**Issue by nurikabe** [yobasystems/alpine-grav#3]
I think `php7-simplexml` may be required.

**Comment by dominictayloruk** [comment]
I will add it, makes the image only marginally bigger.

**Comment by dominictayloruk** [comment]
Done, see https://github.com/yobasystems/alpine-grav/commit/d07a49667f337e649be1d76524e213a42c1e6fc5

**Comment by nurikabe** [comment]
That did it. Thanks!
