### ISSUE TITLE
Let's Encrypt Certbot

### ISSUE THREAD

**Issue by nurikabe** [yobasystems/alpine-grav#4]
Added optional Certbot support here:  https://github.com/nurikabe/alpine-grav

If a `LETSENCRYPT_EMAIL` env var is defined, then this will install certs, configure Nginx to redirect traffic to SSL, and install a daily cert renew cron.  Otherwise operate as normal.

LMK know if you'd like a PR and I'll update the README and send one through.

**Comment by dominictayloruk** [comment]
I wouldn't have merged this as all SSL termination happens at the load balancer not within the container.

Feel free to fork though if it fits your use case.
